### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by affonso** [lilliputten/jsrtf#2]
Hello! Congrats on your initiative!
Can this code be used directly in the browser?

**Comment by lilliputten** [comment]
Yes, this module was used on the client side in real project.

I used the `jsRTF = require('jsrtf')` commands which was later interpreted by webpack.

But keep in mind that the lib implements a very limited subset of the rtf specification.

**Comment by affonso** [comment]
Perfect! 
Thank You, @lilliputten !
