### ISSUE TITLE
How to encode Win-1251 and special characters, for example `Abc Ø абв`?

### ISSUE THREAD

**Issue by Gennady-G** [lilliputten/jsrtf#4]
Greetings @lilliputten!
Thank You for jsrtf library! This is not an issue but a question..

Can You please help mу how to encode non-latin (russian) letters, that are mixed with special symbols, for example: > Abc Ø абв
Here is english text, special symbol and russian text.

I have existing RTF template with 'placeholder' text inside, and what I need is to replace this 'placeholder' with 'Abc Ø абв':
![s1-2023-09-27_182041](https://github.com/lilliputten/jsrtf/assets/5569346/98c6ed94-cbed-43be-a26c-7581673fecef)

If I use Your function `utf8_decode_to_win1251` - it successfully writes russian letters but finally I get "**Ш**" Instead of '**Ø**':
![s2-2023-09-27_175823](https://github.com/lilliputten/jsrtf/assets/5569346/3c0a1cc8-5e4c-4e54-917a-cf3faacde549)

Here is my example code and input and output files:
input rtf: https://mega.nz/file/CtNB2CiY#yid1nLq9P6Jo8zSRAsXeGai-mZLV6xP1OvN1jDpFyG4
output generated by the code below: https://mega.nz/file/asMExKJI#q8oRn1J9oWMlUck6tJ6MdpVGiIjt81kNFRo7T3eSBTU

```
const http = require('http');
const port = 3100;

function utf8_decode_to_win1251(srcStr) {
  var tgtStr = "",
    c = 0;
  for (var i = 0; i < srcStr.length; i++) {
    c = srcStr.charCodeAt(i);
    if (c > 127) {
      if (c > 1024) {
        if (c === 1025) {
          c = 1016;
        } else if (c === 1105) {
          c = 1032;
        }
        c -= 848;
      }
      // c = c % 256; // ???
    }
    tgtStr += String.fromCharCode(c);
  }
  return tgtStr;
}


const server = http.createServer(function (req, res) {

  const fs = require('fs');

  // read existing file
  fs.readFile("C:\input.rtf", "utf8", (err, inputText) => {
    if (err) {
      console.error(err);
      return;
    }

    // I want to replace 'placeholder' text in file with this test text:
    let text = `Abc Ø абв`; // Abc Ø абв

    text = utf8_decode_to_win1251(text); // text with encoded russian letters 'Abc Ø àáâ'

    // replace placeholder from input RTF with text with non-latin characters 'Abc Ø àáâ':
    inputText = inputText.replace("placeholder", text);

    // RTF uses 8-bit so need to convert from unicode
    let buf = Buffer.from(inputText, "ascii"); // "binary" also gives wrong output text https://stackoverflow.com/a/34476862/348736


    // write output file to disk
    fs.writeFile("C:\output.rtf", buf, function (error, resultFile) { // result file contains 'Abc Ш абв', which is wrong..
      if (!error) {
        console.info('Created file', resultFile);
      }
      else {
        console.error(error);
      }
    });
  });
});


server.listen(port, function (error) {

  if (error) {
    console.log(`${error}`);
  } else {
    console.log(`listening on port ${port}`);
  }
})
```

I use LibreOffice v. 7.6.1.2 (X86_64) to view RTF files

**Comment by lilliputten** [comment]
Hi! Sorry, I don't have enough time to try to take a look at this problem. Probably, I'll try to look one of these days.

And one more thing: I haven't touched this project for several years. I think it'll take me some time to remember how all those thing works there.

**Comment by Gennady-G** [comment]
Than You @lilliputten !

Only if You have free time. Think my question is not related with Your encoding function and Your project, looks like it is working Ok - I get result as "Abc Ø àáâ" (russian-letters are encoded ok here, and this symbol exists on this step).. 

But I possibly loose this 'Ø' when convert to binary data in this string: 

`let buf = Buffer.from(inputText, "ascii"); `

Other [Buffer encoding options](https://stackoverflow.com/questions/34476754/what-encodings-does-buffer-tostring-support/34476862#34476862) give wrong results too.. Have no clue how to fix it oO

**Comment by Gennady-G** [comment]
Hi Igor!

So I finally resolved this after few days :-D 

There was mashup of encodings in "Abc Ø абв" and I can't convert the [whole text in Win-1251 or Win-1252](https://www.ascii-code.com/compare/CP1252-vs-CP1251). 

![shaa-2023-09-29_225122](https://github.com/lilliputten/jsrtf/assets/5569346/2b4fbdf0-074d-4633-8fe1-4ac5bbe22296)

Because Win-1251 does not contain "Ø" and Win-1251 does not contain "абв"..

I didn't want to insert unicode, but the only way I see is to convert all text with such symbols as [\u1234?](https://stackoverflow.com/a/7894915/348736). So created this function:

```
function unicode_to_rtf_representation_u(srcStr) {
  if (srcStr == undefined) return "";

  let tgtStr = "";

  for (var i = 0; i < srcStr.length; i++) {
    let c = srcStr.charCodeAt(i);
    let result = "\\u" + c + "?";

    tgtStr += result; 
  }
  console.log("result strings is: " + tgtStr);
  return tgtStr;
}
```
it does something like

> Abc Ø абв --> \u65?\u98?\u99?\u32?\u216?\u32?\u1072?\u1073?\u1074?

and this works..
